site_name: مركز التدريب في قسم هندسة الطيران والفضاء - KFUPM



nav:
  - لل: index.md
  - rr2: test1.md





repo_url: https://github.com/ibrahimaljalal/test758
repo_name: ibrahimaljalal/test758
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  language: ar
  favicon: assets/favicon.png
  logo: assets/favicon.png
  features:
    - content.action.edit
    - content.action.view
    - navigation.footer
  icon:
    edit: material/pencil 
    view: material/eye


extra:
  generator: false
  social:
    - icon: fontawesome/brands/instagram
      link: https://fosstodon.org/@squidfunk
      name: squidfunk on Fosstodon

# plugins:
#   - git-revision-date-localized:
#       enable_creation_date: true






  

  





